sufficient_loss: 0.0008
ddim_steps: 10
ddim_eta: 0.
noise_optimization:
  opt_iters: 10
  log_every: 1
  lr: 0.1
  batch_size:  8 
  uncond_guidance_scale: 1.

conditioning_optimization:
  opt_iters: 10
  log_every: 1
  lr: 0.01
  N_tokens: 10
  batch_size:  8
  uncond_guidance_scale: 1.
  fixed_timesteps: True # non-deterministic results with False

uncond_guidance_scale: 1.
path2save_prefix: './results/experiments/inversion/'
shape: [4,64,64]
device: 'cuda:0'
batch_size:  1
f: 8
save_reconstruction: True